trigger:
  branches:
    include:
      - master
  paths:
    include:
      - server

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: Install .NET Core CLI
    inputs:
      version: 3.0.x

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      zipAfterPublish: True
      publishWebProjects: True
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: AzureWebApp@1
    displayName: Deploy to Azure
    inputs:
      appName: 'cabinizer'
      appType: 'webAppLinux'
      azureSubscription: 'cabinizer'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
